CREATE TABLE `employees` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`ma_nv` text NOT NULL,
	`ho_ten` text NOT NULL,
	`gioi_tinh` text,
	`ngay_sinh` text,
	`thang_sinh` integer,
	`cccd` text,
	`ngay_cap_cccd` text,
	`noi_cap_cccd` text,
	`dia_chi_thuong_tru` text,
	`dia_chi_tam_tru` text,
	`phuong_xa` text,
	`quan_huyen` text,
	`tinh_thanh` text,
	`sdt` text,
	`email` text,
	`tinh_trang_hon_nhan` text,
	`nguoi_lien_he_khan_cap` text,
	`moi_quan_he` text,
	`sdt_nguoi_than` text,
	`nghe_nghiep` text,
	`vi_tri` text,
	`cap_bac` text,
	`phong_ban` text,
	`quan_ly_truc_tiep` text,
	`trinh_do_hoc_van` text,
	`chuyen_nganh` text,
	`ngay_thu_viec` text,
	`ngay_chinh_thuc` text,
	`ngay_ky_hop_dong` text,
	`tham_nien` text,
	`thang_dong_bhxh` text,
	`so_hdld_cu` text,
	`trang_thai_hd` text,
	`ngay_ky_hdtv` text,
	`ngay_ket_thuc_hdtv` text,
	`ngay_ky_hdld_xdth_1` text,
	`ngay_ket_thuc_hdld_xdth_1` text,
	`ngay_ky_hdld_xdth_2` text,
	`ngay_ket_thuc_hdld_xdth_2` text,
	`ngay_ky_hdld_kxdth` text,
	`so_hdld_moi_nhat` text,
	`so_so_bhxh` text,
	`muc_dong_bhxh_cu` real,
	`muc_dong_bhxh_moi` real,
	`stk_ngan_hang` text,
	`luong_gross_thu_viec` real,
	`luong_gross_chinh_thuc` real,
	`phu_cap` real,
	`luong_dieu_chinh_1` real,
	`ngay_hieu_luc_1` text,
	`luong_dieu_chinh_2` real,
	`ngay_hieu_luc_2` text,
	`luong_dieu_chinh_3` real,
	`ngay_hieu_luc_3` text,
	`luong_gross_hien_tai` real,
	`ngay_hieu_luc_hien_tai` text,
	`trang_thai` text DEFAULT 'Đang làm việc' NOT NULL,
	`ngay_nghi_viec` text,
	`ly_do_nghi` text,
	`ghi_chu` text,
	`created_at` text DEFAULT (datetime('now', 'localtime')),
	`updated_at` text DEFAULT (datetime('now', 'localtime'))
);
--> statement-breakpoint
CREATE UNIQUE INDEX `employees_ma_nv_unique` ON `employees` (`ma_nv`);